### ISSUE TITLE
Meta: Build system changes

### ISSUE THREAD

**Issue by technosophos** [helm/helm#1968]
There are a number of requests and PRs for adding new build targets, artifacts, and so on. This is a meta-issue to bring all of those together and maybe open a discussion on making some bigger changes to the CI/CD pipeline.

The high-level requirements are:

- Developer builds (on local workstations) should not require cross-compiles
- CI/CD builds for PRs should take fewer than 10 minutes
- Canary builds should trigger on merge to `master`, and should build the same targets as used for production releases
- Production releases should build all production targets, following the official Kubernetes guidelines
- canary and production builds should not backup the CI/CD queue so that PR requests cannot run
- Whatever CI/CD system we use (currently CircleCI) should allow any visitor to see what is currently happening in the build pipeline.

Currently unresolved related issues and PRs:

- [x] Issue #1862 (Docker images)
- [x] PR #1929 (helm docker image)
- [x] PR #1930 (ppc build)
- [x] Issue #1690 (distribute Tiller binary)
- [x] Issue #1649 (native macOS builds)
- [x] Issue #1320 (build Docker image with Helm binary)
- [x] Issue #1981 (URL to helm binary)
- [x] Issue #2274 (`latest` URL for download)

**Comment by kfox1111** [comment]
sounds good to me.

**Comment by wilkers-steve** [comment]
Let me know if I can help with this @technosophos.  Issue #1690 in particular would be helpful for CI purposes on our end.  I'd like to be able to help with enabling CICD processes in general, so happy to help here.

**Comment by mkumatag** [comment]
Anything happening in this front? Only 3 more weeks left for the mentioned milestone!

**Comment by luxas** [comment]
Also very much related, please merge https://github.com/kubernetes/helm/pull/2649 as I already made that change for you :)

**Comment by thomastaylor312** [comment]
This is a meta issue, so I am going to pull it off of any milestone

**Comment by vielmetti** [comment]
Though this issue has moved to "frozen", there are still a number of dependencies on the build system changing. Can we get an update on what the expected goals and timelines are for this?

Looking particularly in this case at getting "tiller" binaries for arm64, #3269 as stuck behind this.

**Comment by bacongobbler** [comment]
I just had another look at this ticket. It looks like the rest of the issues center around providing different architecture images for tiller. AFAIK @alicefr is interested in resolving the problem in a generic way, so I'd definitely get in contact to work on a solution together.

**Comment by bacongobbler** [comment]
> Can we get an update on what the expected goals and timelines are for this?

Already done

**Comment by bacongobbler** [comment]
> which I can ship a quick one-liner PR for that.

https://github.com/helm/helm/pull/4443

**Comment by bacongobbler** [comment]
closing as all the TODOs on the list are either implemented or closed as irrelevant for Helm 3. If there are things we can improve with the CI system, please open a new ticket. Thanks!
