### ISSUE TITLE
[META] Works on Windows, yet?

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#2456]
Helm has some bugs when it comes to working on and with Windows. Filing as a high level ticket to track windows support, unless there is another way.

* [x] #2362 Helm init failed on windows
* [x] #2396 Failed to install vendor dependencies on Windows
* [x] #2420 Support Tiller installs in clusters with Windows nodes
* [ ] #1606 Add AppVeyor CI support for Windows testing
* [x] #2071 Error: open .helm\repository\cache\local-index.yaml
* [x] #2252 Error using repo add

There are more issues still to be determined.

**Comment by thomastaylor312** [comment]
This is great. Thanks for doing this @mattfarina

**Comment by bacongobbler** [comment]
This would be a fantastic use case for a Github Project to track ticket progress. "Windows Conpatibility", perhaps?

**Comment by thomastaylor312** [comment]
I have been wanting to do that for a while, I was waiting for people to get used to the new developer workflow, so now may be a good time

**Comment by bacongobbler** [comment]
At the very least the server-side commands like `helm install` and `helm init` all work on Windows, so that's good!

I'll see what I can do about the `repo add` and local-index issues this release.

**Comment by bacongobbler** [comment]
Tacked on #3219 to the list.

**Comment by bacongobbler** [comment]
https://github.com/kubernetes/helm/issues/4304 is another windows-specific bug

/remove-lifecycle stale

**Comment by bacongobbler** [comment]
another bug: #4418

**Comment by bacongobbler** [comment]
appveyor support has been added in #4136 and will kick in after the 2.10 release cycle. At that point, I think there's only a few more bugs to consider Helm fully working on Windows!
