### ISSUE TITLE
Helm 3: Test Enhancement Proposal

### ISSUE THREAD

**Issue by jlegrone** [helm/helm#6020]
### Features

- [x] Support defining tests as `Jobs` (#6054)
- [x] Enable the management of resources (eg. service accounts, network policy, configmaps) to be made available during test execution (#6054)
- [ ] Stream execution logs & events with a flag (eg. `--verbose`) -- see issues #2298 and #3481
- [x] Enable control over resource deletion behavior on a per-resource basis (may be overridden globally with a flag, eg. `--skip-hook-cleanup`) (#6054)

### Breaking Changes

- [x] Remove `test-failure` hook ([only 20 usages public on Github](https://github.com/search?l=YAML&q=helm.sh%2Fhook+test-failure&type=Code)) (#6054)
- [x] Remove the existing `--cleanup` flag (#6363)
- [ ] Make resource cleanup the default (on success OR failure), and add a flag to skip cleanup for all resources (`--skip-hook-cleanup`)

### Deprecations

- [x] Rename the `test-success` annotation value to `test`. Keep supporting `test-success` but log a warning to the user. (#6054)

### 3.x and Beyond

1. Surface relevant logs and k8s events to users during hook execution or on failure
1. Support structured output with `--output json`, eg:
   ```json
   {
     "logs": [
       {
         "pod": "foo",
         "output": "helloworld"
       }
     ],
     "events": [
       {
         "apiVersion": "v1",
         "involvedObject": {
           "apiVersion": "v1",
           "kind": "Pod",
           "name": "foo"
         },
         "message": "Created container bar",
         "reason": "Created"
       }
     ]
   }
   ```

## Implementation

1. Specify tests and supporting resources with the `helm.sh/hook: test` annotation
1. Converge the business logic for test execution, log output, deletion policy, etc with existing hook implementations
1. Add a `--skip-hook-cleanup` flag to `install`, `upgrade`, `delete`, and `test` commands which will override per-resource `helm.sh/hook-delete-policy` behavior
1. Eventually support log streaming and printing of related events on failure for all Helm hooks

## Other Considerations

Some of the desired features for `helm test` (1 and 2) are already supported by the hook system, while the others would likely be welcome enhancements to existing hooks.

Continuing to share the hooks annotation-based API with `test` is advantageous in that users have only one API to learn, and if desired some tests may also be executed as hooks. The latter is a use case for charts that define "smoke" tests which can do things like prevent upgrades when the target release is in a bad state.

None of the enhancements outlined in this issue are likely to be blocked by continuing to use the hooks API, however in the future there is a possibility that the hooks API will not be sufficient for some unforeseen testing use cases. We have the opportunity to make a breaking change in Helm 3 and move to a separate API for test annotations which could evolve independently of hooks, however this comes at a large cost and may be premature if we lack well defined use cases predicated on the API.

**Comment by jeremy-donson** [comment]
In general, moving testing, dependency mgt, change management, etc
to standard command features will give helm HUGE steps forward.

I would gladly discuss any and all,
and this bears broad discussion across languages and services.

**Comment by michelleN** [comment]
Excellent write up @jlegrone. I think you've come up with an excellent proposal and I appreciate your perspective as an end user. It's a good evolution from what `test` is doing now and lays a solid foundation for evolving the `test` experience in the future. I can see where we might also be able to evolve this into support for test suites or even running single tests as has been requested recently.

Some questions:
1. Would you still support `Pods` in this scenario or move entirely to supporting `Jobs`?
2. How do you handle the scenario where a user wants to leave test pods around to inspect in case of a failure? This has been a big ask in the community.

**Comment by bacongobbler** [comment]
Thanks for the write-up @jlegrone. As discussed in the call, it may make sense to work on the infrastructure to support these use cases so we can avoid delaying a 3.0 release. Laying out the groundwork would be a good first step, then we can start discussing feature additions proposed, such as log streaming support, Job support, etc. in a future 3.x release.

Are you looking to do this work yourself, or are you looking for others to implement the work? Just trying to gauge what needs to happen to get the ball rolling on this. Thanks!

**Comment by bacongobbler** [comment]
I also want to make sure that we have a story for users migrating from Helm 2 to Helm 3. What's changed, why we're changing it, how to migrate etc.

**Comment by jlegrone** [comment]
@michelleN

> Would you still support `Pods` in this scenario or move entirely to supporting `Jobs`?

We'll support whatever is supported by hooks in helm 3. I wouldn't mind switching entirely to jobs but that would be a pretty major change so it's probably best to continue supporting both.

> How do you handle the scenario where a user wants to leave test pods around to inspect in case of a failure?

This should be possible with the `helm.sh/hook-delete-policy` annotation. Eg. always leave resources around for inspection:

```yaml
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
```

Or only skip cleanup on failure:

```yaml
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
```

The proposed `--skip-hook-cleanup` flag can be added after 3.0, but would also help address debugging use cases when working with charts that may not directly expose those annotations.

@bacongobbler 

> Are you looking to do this work yourself, or are you looking for others to implement the work? Just trying to gauge what needs to happen to get the ball rolling on this.

Right now the plan is to work with @michelleN on implementing required changes for 3.0, and we can break out new features for 3.1+ releases into independent github issues. I'm definitely happy to take on some of the development effort!

**Comment by bacongobbler** [comment]
removing from the beta milestone as #6185 has been PR'd, which means this discussion can move forward without blocking the release.

**Comment by bacongobbler** [comment]
Hi @jlegrone. Going forward, please write proposals in helm/community so that we have a record of this (see also https://github.com/helm/community/pull/140 on a proposal (ha!) to write a proposal going forward.

Given that the functionality proposed here has been merged, we can consider this resolved. If not, please open a proposal over at helm/community. Thanks!
