### ISSUE TITLE
[tracker] OCI-related changes for v3.3.0

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#8252]
This ticket is to track a collection of pull requests related to OCI supported that we should try to get merged to be included in the upcoming v3.3.0 release:

- [ ] ~~https://github.com/helm/helm/pull/8216~~
- [x] https://github.com/helm/helm/pull/8249
- [x] https://github.com/helm/helm/pull/8254
- [x] https://github.com/helm/helm/pull/8220
- [ ] ~~https://github.com/helm/helm/pull/8199~~
- [x] https://github.com/helm/helm/pull/8089 or https://github.com/helm/helm/pull/7236 (duplicates)
- [x] https://github.com/helm/helm/pull/7356
- [ ] https://github.com/helm/helm/pull/7613 (size/XL)

**Comment by bacongobbler** [comment]
I've gone ahead and added these tickets to the 3.3.0 milestone.

**Comment by jdolitsky** [comment]
I'd reluctantly pull #8216 and #8090 out of this list in order to unblock 3.3 release, but I think we should definitely try to get #8249 and #7613 if possible (especially #7613) cc @bacongobbler

**Comment by bacongobbler** [comment]
Looking at the list, the only thing left is #7613, which has been bumped to 3.4. The rest has all been addressed, so we can close this now. Thanks for bringing this up.
